### ISSUE TITLE
Error: incorrect header check when sending a request to a SPDY server

### ISSUE THREAD

**Issue by misterdjules** [nasss/spdy-client#1]
When running the client-test.js tests suite, I get the following ouput:

```
 ✖ 7 of 7 tests failed:

  1) A SPDY Client tls request, GET:
     Error: incorrect header check
      at Zlib._binding.onerror (zlib.js:295:17)
```

Also, when I write a simple server using node-spy:

```
#!/usr/bin/env node

var spdyServer = require('spdy');
var SPDY_SERVER_PORT = 4243;
var useInternalSPDYServer = true;

var fs = require('fs');
var options = {
    plain: true,
    ssl : true,
    key : fs.readFileSync('./keys/spdy-key.pem'),
    cert: fs.readFileSync('./keys/spdy-cert.pem'),
    ca  : fs.readFileSync('./keys/spdy-csr.pem')
};

var server = spdyServer.createServer(options, function(req, res) {
  res.writeHead(200);
  res.end('hello world!\n');
  console.log('Handled SPDY request!');
});

server.listen(SPDY_SERVER_PORT);
```

and that I send a SPDY request using the following simple client:

```
var spdyClient = require('./lib/spdy-client/client.js');

var req = spdyClient.get(
                {
                    method: 'GET',
                    path: '/',
                    url : '/',
                    port: 4243,
                    host: 'localhost'
                },
                function(response) {
                        logger.info("--- GET  RESPONSE --");

                        response.once('data', function (chunk) {
                                var data = String.fromCharCode.apply(null, new Uint16Array(chunk));
                                logger.info(data);

                        });    

                }); 

req.on('error', function(err){        
      console.log('Error in sendSpdyGetRequest');
      logger.error(err);
}); 
```

I get the same error:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: incorrect header check
    at Zlib._binding.onerror (zlib.js:295:17)
```

although the request has been handled by the SPDY server:

```
misterdjules@misterdjules-VirtualBox:~/playground/spdy-ws-test$ ./node_spdy_server.js 
Enter PEM pass phrase:
Handled SPDY request!
```

If I use spdycat to send the request to the same server, it works. Here's the output of spdycat (with verbosity on):

```
misterdjules@misterdjules-VirtualBox:~/playground/spdy-ws-test$ ./tools/spdycat -v http://127.0.0.1:4243/
[  0.002] NPN select next protocol: the remote server offers:
          * spdy/3
          * spdy/2
          * http/1.1
          * http/1.0
          NPN selected the protocol: spdy/3
[  0.021] Handshake complete
[  0.022] send SYN_STREAM frame <version=3, flags=1, length=216>
          (stream_id=1, assoc_stream_id=0, pri=3)
          :host: 127.0.0.1:4243
          :method: GET
          :path: /
          :scheme: http
          :version: HTTP/1.1
          accept: */*
          accept-encoding: gzip, deflate
          user-agent: spdylay/0.3.8
[  0.024] recv SETTINGS frame <version=3, flags=0, length=20>
          (niv=2)
          [4(1):100]
          [7(1):1048576]
[  0.060] recv SYN_REPLY frame <version=3, flags=0, length=30>
          (stream_id=1)
          :status: 200 OK
          :version: HTTP/1.1
hello world!
[  0.061] recv DATA frame (stream_id=1, flags=0, length=13)
[  0.061] recv DATA frame (stream_id=1, flags=1, length=0)
[  0.061] send GOAWAY frame <version=3, flags=0, length=8>
          (last_good_stream_id=0)
misterdjules@misterdjules-VirtualBox:~/playground/spdy-ws-test$
```

Any idea of what could be wrong?

**Comment by misterdjules** [comment]
I also did a test with two cases:

1) I used spdy-client to send a GET request to spdyd (a server from the spdylay project, from which spdycat comes). The request is sent to the server, but it seems it is not complete. Here's the trace (using spdyd -v for verbosity):

```
The negotiated next protocol: spdy/3
[id=1] [  6.810] send SETTINGS frame <version=3, flags=0, length=12>
          (niv=1)
          [4(0):100]
[id=1] [  6.819] recv SYN_STREAM frame <version=3, flags=2, length=78>
          (stream_id=1, assoc_stream_id=0, pri=0)
          :host: 127.0.0.1
          :method: GET
          :path: /
          :port: 4243
          :url: /
          :version: HTTP/1.1
```

2) I used spdycat to send a GET request to spdyd. It works as expected, here's the trace:

```
The negotiated next protocol: spdy/3
[id=1] [  4.395] recv SYN_STREAM frame <version=3, flags=1, length=216>
          (stream_id=1, assoc_stream_id=0, pri=3)
          :host: 127.0.0.1:4243
          :method: GET
          :path: /
          :scheme: http
          :version: HTTP/1.1
          accept: */*
          accept-encoding: gzip, deflate
          user-agent: spdylay/0.3.8
[id=1] [  4.397] send SETTINGS frame <version=3, flags=0, length=12>
          (niv=1)
          [4(0):100]
[id=1] [  4.397] send SYN_REPLY frame <version=3, flags=0, length=102>
          (stream_id=1)
          :status: 404 Not Found
          :version: HTTP/1.1
          content-encoding: gzip
          content-type: text/html; charset=UTF-8
          date: Wed, 08 May 2013 21:26:48 GMT
          server: spdyd spdylay/0.3.8
[id=1] [  4.398] send DATA frame (stream_id=1, flags=0, length=124)
[id=1] [  4.403] send DATA frame (stream_id=1, flags=1, length=0)
[id=1] [  4.403] stream_id=1 closed
[id=1] [  4.403] recv GOAWAY frame <version=3, flags=0, length=8>
          (last_good_stream_id=0)
[id=1] [  4.403] closed
```

It seems spdycat sends the header  _accept-encoding: gzip, deflate_ , which seems related to my issue.

**Comment by nasss** [comment]
You need a patched version of spdy server : 

https://github.com/nasss/node-spdy/commit/6b979dcf3a07c957a765e5c46596daa013867748

**Comment by misterdjules** [comment]
Thank you very much, it works now. I had installed node-spdy via npm a few
days ago. I grabbed the latest release from npm that includes your fix.
Thank you again!

On Thu, May 9, 2013 at 7:46 AM, nasss notifications@github.com wrote:

> You need a patched version of spdy server :
> 
> nasss/node-spdy@6b979dchttps://github.com/nasss/node-spdy/commit/6b979dcf3a07c957a765e5c46596daa013867748
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nasss/spdy-client/issues/1#issuecomment-17660410
> .

## 

Julien
